version: '3.2'

services:
  web:
    build: services/php-server
    container_name: aether3
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - type: bind
        source: ${APP_PATH_HOST}
        target: ${APP_PATH_CONTAINER}
      - type: bind
        source: ${AETHER3_ME_CONF_HOST}
        target: ${AETHER3_ME_CONF_CONTAINER}
      - type: bind
        source: ${AETHER3_ME_PHP_INI_HOST}
        target: ${AETHER3_ME_PHP_INI_CONTAINER}
      - type: bind
        source: ./config/yaml/yaml.ini
        target: /etc/php/7.0/apache2/conf.d/20-yaml.ini
      - type: bind
        source: ./config/xdebug/xdebug-cli.ini
        target: /etc/php/7.0/cli/conf.d/20-xdebug.ini
      - type: bind
        source: ./config/yaml/yaml.ini
        target: /etc/php/7.0/cli/conf.d/20-yaml.ini
      - type: bind
        source: ./config/xdebug/docker-php-ext-xdebug.ini
        target: /etc/php/7.0/mods-available/xdebug.ini
      - type: bind
        source: ./config/yaml/yaml.ini
        target: /etc/php/7.0/mods-available/yaml.ini
      - type: bind
        source: ./logs/apache-logs
        target: /var/log/apache2
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}
    networks:
      backend:
        ipv4_address: 172.16.238.10
    extra_hosts:
    - aether3.me:127.0.0.1

  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - type: bind
      source: ${DB_PATH_HOST}
      target: /var/lib/mysql
    - type: bind
      source: ./logs/mysql-logs
      target: /var/log/mysql
    networks:
      backend:
        ipv4_address: 172.16.238.11

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
    - db:mysql
    ports:
    - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD},
      PMA-HOST: mysql
    networks:
      backend:
        ipv4_address: 172.16.238.12

  composer:
    build: services/composer
    container_name: composer-a
    volumes:
      - type: bind
        source: ${APP_PATH_HOST}
        target: ${APP_PATH_CONTAINER}

    working_dir: ${APP_PATH_CONTAINER}
    command: install
    networks:
      backend:
        ipv4_address: 172.16.238.13

  memcached:
    image: memcached:alpine
    container_name: memcached
    command: ["-m", "512m"]
    ports:
      - "11211:11211"
    networks:
      backend:
        ipv4_address: 172.16.238.14

  phpmemcachedadmin:
    image: jacksoncage/phpmemcachedadmin
    container_name: phpmemcachedadmin
    ports:
    - 8282:80
    networks:
      backend:
        ipv4_address: 172.16.238.16

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
